### ISSUE TITLE
what i do wrong 

### ISSUE THREAD

**Issue by sec13b** [Tylous/Freeze#3]
I try this below commands:
`./Freeze -I a.exe -encrypt -sandbox -O bypassTest.exe`
`./Freeze -I a.exe -O bypassTest7.exe -encrypt -process "C:\\Windows\\System32\\notepad.exe"`
`./Freeze -I a.exe -encrypt -process C:\Windows\System32\notepad.exe -sandbox -O bypassTest2.exe`
`./Freeze -I a.exe -O bypassTest3.exe -process MsMpEng.exe -sandbox`
` ./Freeze -I a.exe -encrypt -sandbox -O bypassTest4.exe`
`./Freeze -I a.exe -encrypt -sandbox -O bypassTest5.exe`
 `./Freeze -I a.exe -encrypt -process C:\Windows\Temp\ -sandbox -O bypassTest6.exe`

After i test to vmware wind10 , and also a wind10 , does not run

**Comment by Xpatr0nX** [comment]
Don't use `-sandbox `

**Comment by Tylous** [comment]
what @fk4125 said
